# -*- coding: utf-8 -*-
"""A1P4_6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sBOOUjTb9fa1GGAKEbJn86bAw7IHV1_b
"""

class SkipGramNegativeSampling(torch.nn.Module):
    def __init__(self, vocab_size, embedding_size):
      super().__init__()
      self.embedding = torch.rand(vocab_size, embedding_size, requires_grad = True)

    def forward(self, x, t):
      prediction = torch.einsum('ab, ac -> a',self.embedding[x], self.embedding[t]) #elementwise inner product
      return prediction