# -*- coding: utf-8 -*-
"""A4_4_4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5_3TQBxJZqILwNq8bMoQ_556UgUDFyH
"""

pip install openai
#please run this in colab if you want to test it

pip install cohere

pip install tiktoken

import os
import openai
import csv
from openai import OpenAI

client = OpenAI(
    api_key= "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",
)

responses = []
prompt = "Without making definitive statements, soften the following statement so as not to accuse them or speak on their behalf: "

with open('DirectStatements.csv') as ds:
  reader = csv.reader(ds, delimiter = ',')
  for i,line in enumerate(reader):
    if i > 28:
      chat_completion = client.chat.completions.create(
        messages=[
            {
                "role": "user",
                "content": prompt+line[0],
            }
        ],
            model="gpt-3.5-turbo",
      )
      gpt_response = chat_completion.choices[0].message.content
      print("Original statement: ")
      print(line[0])
      print("GPT Response: ")
      print(gpt_response)
      valid = str(input("Is this a softened statement? "))
      responses += [[line[0], gpt_response, valid]]

with open('Responses.csv', 'w') as r:
  writer = csv.writer(r, delimiter = ',')
  for response in responses:
    writer.writerow(response)